### ISSUE TITLE
Opencast admin dashboard UI 

### ISSUE THREAD

**Issue by techiexplorer** [mtneug/containerized-opencast-workshop#1]
#Query, were you able to access the admin console when OC is installed on kubernetes?

**Comment by mtneug** [comment]
If I remember correctly, sure I was able.

Please note that these examples were prepared for the Opencast Summit some years ago and even then were not meant as production-ready workload definitions. Writing proper Helm charts / Kubernetes operator is still on my agenda, but pushed back for a while now.

**Comment by techiexplorer** [comment]
Oh okay. I am trying to install opencast on Kubernetes pods manually by creating pods and configuring them, which obviously is a bit of a headache task. Could you please point me to the right direction in doing this? Thanks a lot!
